# Generated by Django 2.1.7 on 2019-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
                ('updateTime', models.DateTimeField(max_length=10000)),
                ('categoryName', models.CharField(max_length=10000)),
                ('method', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=10000)),
                ('addr', models.CharField(max_length=10000)),
                ('categoryContent', models.CharField(max_length=100000)),
            ],
        ),
    ]
