# Generated by Django 2.1.7 on 2019-12-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191219_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'managed': True},
        ),
    ]
