# Generated by Django 2.1.7 on 2019-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191219_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={},
        ),
    ]
