# Generated by Django 3.0.1 on 2019-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20191223_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='addr',
            field=models.CharField(max_length=1001),
        ),
        migrations.AlterField(
            model_name='talent',
            name='age',
            field=models.IntegerField(),
        ),
    ]
